"""Moved verbatim from streamlit_app.py (refactor/modularize). No logic changes."""

import streamlit as st

from dfs_lab import styles
from dfs_lab.config import APP_BUILD
from dfs_lab.ui import setup, main


def render_app():
    """Top-level app flow (moved verbatim from streamlit_app.py)."""
    if st.session_state.get("_app_build") != APP_BUILD:
        st.session_state["_app_build"] = APP_BUILD
        # Prevent a newly deployed build from displaying an answer generated by older code.
        st.session_state.pop("classic_ai_chat", None)
        st.session_state.pop("classic_ai_error", None)
        st.session_state.pop("classic_ai_model", None)
        # A deployed optimizer change must never keep a portfolio built by older rules.
        st.session_state.pop("showdown_result_v4", None)
        st.session_state.pop("classic_result_v4", None)
        st.session_state.pop("world_explorer_pick", None)
        st.session_state.pop("lineup_lab_pick", None)
        st.markdown(styles.GLOBAL_CSS, unsafe_allow_html=True)
        st.markdown(styles.SIDEBAR_V26_CSS, unsafe_allow_html=True)
        settings = setup.render_setup()
        main.render_main(settings)