"""Moved verbatim from streamlit_app.py (refactor/modularize). No logic changes."""

import streamlit as st

from dfs_lab import styles
from dfs_lab.config import APP_BUILD
from dfs_lab.ui import setup, main, persist
from dfs_lab.ui import nav as _nav


def _maybe_resume_page():
    """After a fresh session restore, land back on the page the user was on.

    Runs once per session, right after settings are established (boot_page
    requires them). Validated against the nav registry so a renamed page can
    never trap the app in a redirect loop.
    """
    if not st.session_state.pop("_persist_resume_done", False):
        return
    target = (st.session_state.get("_persist_blob") or {}).get("page")
    valid = {f for _, f in _nav.pages_for("Classic")} | \
            {f for _, f in _nav.pages_for("Showdown")} | \
            set(_nav.STORY_PAGES.values())
    if target in valid and target != "streamlit_app.py":
        st.switch_page(target)


def render_app():
    """Top-level app flow (moved verbatim from streamlit_app.py)."""
    # 'Aytia remembers': seed inputs from the URL before any widget renders,
    # so a tab killed by iOS Safari reopens exactly as the user left it.
    restored = persist.restore()
    if restored:
        # One-shot: the entry page may bounce the user back to their page
        # once settings exist below.
        st.session_state["_persist_resume_done"] = True
    if st.session_state.get("_app_build") != APP_BUILD:
        st.session_state["_app_build"] = APP_BUILD
        # Prevent a newly deployed build from displaying an answer generated by older code.
        st.session_state.pop("classic_ai_chat", None)
        st.session_state.pop("classic_ai_error", None)
        st.session_state.pop("classic_ai_model", None)
        # A deployed optimizer change must never keep a portfolio built by older rules.
        st.session_state.pop("showdown_result_v4", None)
        st.session_state.pop("classic_result_v4", None)
        st.session_state.pop("world_explorer_pick", None)
        st.session_state.pop("lineup_lab_pick", None)
        st.markdown(styles.GLOBAL_CSS, unsafe_allow_html=True)
        st.markdown(styles.SIDEBAR_V26_CSS, unsafe_allow_html=True)
    # NOTE: everything below must run on EVERY script run, not just the first.
    # It was accidentally indented inside the `if` above during the refactor,
    # which blanked the page on any widget-triggered rerun.
    settings = setup.render_setup()
    # Persist for multipage: pages/*.py boot from session state instead of
    # re-rendering the setup controls.
    st.session_state["aytia_settings"] = settings
    persist.save()
    _maybe_resume_page()
    main.render_main(settings)
    persist.save()